/**
 * Room templates for the layout editor's Rooms tool — ready-made rooms
 * (café, game room, lab…) generated by scripts/asset-gen/room-templates.ts
 * and sent by the host as `roomTemplatesLoaded`. Module-level like the other
 * asset stores: set once on load, read by the toolbar and the canvas.
 */

import type { RoomTemplate } from '../../../shared/protocol.js';

let templates: RoomTemplate[] = [];

export function setRoomTemplates(next: RoomTemplate[]): void {
  templates = next;
}

export function getRoomTemplates(): RoomTemplate[] {
  return templates;
}

export function getRoomTemplate(id: string | null): RoomTemplate | undefined {
  return id ? templates.find((t) => t.id === id) : undefined;
}
